# Configuration for the [cargo-release](https://github.com/sunng87/cargo-release) tool.

pre-release-replacements = [
  {file="README.md", search="quickjs-rusty = .*", replace="{{crate_name}} = \"{{version}}\""},
]

tag-prefix = "quickjs-rusty-"
